const contractABI = [
  "constructor()",
  "event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)",
  "event ApprovalForAll(address indexed owner, address indexed operator, bool approved)",
  "event MarketItemCreated(uint256 indexed tokenId, address seller, address owner, uint256 price, bool sold)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
  "function approve(address to, uint256 tokenId)",
  "function balanceOf(address owner) view returns (uint256)",
  "function cancelListing(uint256 tokenId)",
  "function createMarketItem(uint256 tokenId, uint256 price)",
  "function createMarketSale(uint256 tokenId) payable",
  "function createToken(string tokenURI, uint256 price) payable returns (uint256)",
  "function fetchItemsListed() view returns (tuple(uint256 tokenId, address seller, address owner, uint256 price, bool sold)[])",
  "function fetchMarketItems() view returns (tuple(uint256 tokenId, address seller, address owner, uint256 price, bool sold)[])",
  "function fetchMyNFTs() view returns (tuple(uint256 tokenId, address seller, address owner, uint256 price, bool sold)[])",
  "function getApproved(uint256 tokenId) view returns (address)",
  "function getListingPrice() view returns (uint256)",
  "function getMarketItem(uint256 tokenId) view returns (tuple(uint256 tokenId, address seller, address owner, uint256 price, bool sold))",
  "function isApprovedForAll(address owner, address operator) view returns (bool)",
  "function name() view returns (string)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function resellToken(uint256 tokenId, uint256 price) payable",
  "function safeTransferFrom(address from, address to, uint256 tokenId)",
  "function safeTransferFrom(address from, address to, uint256 tokenId, bytes data)",
  "function setApprovalForAll(address operator, bool approved)",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "function symbol() view returns (string)",
  "function tokenURI(uint256 tokenId) view returns (string)",
  "function transferFrom(address from, address to, uint256 tokenId)",
  "function updateItemPrice(uint256 tokenId, uint256 newPrice)",
  "function updateListingPrice(uint256 _listingPrice) payable"
];

export { contractABI };
